---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - apt-transport-https
    - nginx

- name: Install sury key
  apt_key:
    url: 'https://packages.sury.org/php/apt.gpg'
    state: present

- name: Add sury repositories
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present
    update_cache: yes
    filename: 'sury'

- name: install php dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php7.3
    - php7.3-cli
    - php7.3-intl
    - php7.3-iconv
    - php7.3-fpm
    - php7.3-curl
    - php7.3-gd
    - php7.3-mysql
    - php7.3-mysqli
    - php7.3-opcache
    - php7.3-json
    - php7.3-mbstring
    - php7.3-soap
    - php7.3-xml
    - php7.3-zip
    - php7.3-gmp
    - php7.3-bcmath
    - php-memcached
    - php-xdebug
    - php-redis

- name: Set socket for php-fpm
  ansible.builtin.set_fact:
    socket_php_fpm: "/var/run/php/php7.3-fpm.sock"

- name: Create nginx vhost config
  template:
    src: monicahq.conf.j2
    dest: /etc/nginx/sites-enabled/monica.conf
- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent