---
- include_tasks: install_deps_el8.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- include_tasks: install_deps_stretch.yml
  when: ansible_os_family=="Debian"

- name: Add the user
  user:
    name: monicahq
    shell: /usr/bin/nologin
    home: /home/monicahq
    group: www-data

- name: Recursively change ownership of a directory
  file:
    path: /srv/monicahq
    state: directory
    recurse: yes
    owner: monicahq
    group: www-data
  changed_when: False

- name: check out old branch
  git:
    repo: 'https://github.com/monicahq/monica'
    dest: /srv/monicahq
    version: v2.19.1
  become: yes
  become_user: monicahq

- name: reload service php-fcgi
  become: true
  systemd:
    name: php7.3-fpm
    state: reloaded
  changed_when: False

- name: install composer
  include_role:
    name: geerlingguy.composer

- name: install composer dependencies
  composer:
    command: install
    working_dir: /srv/monicahq
  become_user: monicahq

- name: prepare configuration
  template:
    src: env.j2
    dest: /srv/monicahq/.env
    group: www-data
    mode: '0644'
  become_user: monicahq
  changed_when: False

- name: Run an initial key generation
  command: "/usr/bin/php /srv/monicahq/artisan key:generate"
  args:
    chdir: /srv/monicahq/
  become_user: monicahq
  changed_when: False

- name: Run an initial migration
  command: "/usr/bin/php /srv/monicahq/artisan setup:production --force"
  args:
    chdir: /srv/monicahq/
  become_user: monicahq
  register: diff_cmd
  failed_when: diff_cmd.rc not in [0,1] and "'The given data was invalid' not in diff_cmd.stderr"
  changed_when: False

- name: Place a scheduler cron job
  cron:
    user: monicahq
    name: "scheduler"
    job: "/usr/bin/php /srv/monicahq/artisan schedule:run"

- name: Put right permissions to storage
  file:
    path: /srv/monicahq/storage
    state: directory
    recurse: yes
    mode: g+w

- name: reload service nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
  changed_when: False
