---
- include_tasks: install_deps_el8.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- include_tasks: install_deps_stretch.yml
  when: ansible_os_family=="Debian"

- name: check out old branch
  git:
    repo: 'https://github.com/monicahq/monica'
    dest: /srv/monicahq
    version: v2.19.1

- name: Add the user
  user:
    name: monicahq
    shell: /usr/bin/nologin
    home: /srv/monicahq

- name: Ensure group "www-data" exists
  ansible.builtin.group:
    name: www-data
    state: present

- name: reload service php-fcgi
  become: true
  systemd:
    name: php7.3-fpm
    state: reloaded

- name: install composer
  include_role:
    name: geerlingguy.composer

- name: install composer dependencies
  composer:
    command: install
    working_dir: /srv/monicahq
- name: prepare configuration
  template:
    src: env.j2
    dest: /srv/monicahq/.env

- name: Run an initial key generation
  command: "/usr/bin/php /srv/monicahq/artisan key:generate"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Run an initial migration
  command: "/usr/bin/php /srv/monicahq/artisan setup:production --force"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Place a scheduler cron job
  cron:
    user: monicahq
    name: "scheduler"
    job: "/usr/bin/php /srv/monicahq/artisan schedule:run"

- name: Recursively change ownership of a directory
  file:
    path: /srv/monicahq
    state: directory
    recurse: yes
    owner: monicahq
    group: www-data

- name: Put right permissions to storage
  file:
    path: /srv/monicahq/storage
    state: directory
    recurse: yes
    mode: g+w

- name: reload service nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
