dependency:
  name: galaxy
driver:
  name: podman

platforms:
  # - name: ansible-role-monica-test-debian
  #   image: "geerlingguy/docker-debian9-ansible"
  #   command: ${MOLECULE_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  - name: ansible-role-monica-test-rhel8
    image: geerlingguy/docker-rockylinux8-ansible:latest
    hostname: monica
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/default/playbook.yml
      x:
        - 204  # Lines should be no longer than 160 chars
        - 403  # Package installs should not use latest
        - 502  # All tasks should be named
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra

